### ISSUE TITLE
Remove Child Device

### ISSUE THREAD

**Issue by brad628** [bhamiltoncx/hubitat-modern-forms-fan#1]
Hi, is there a way that I can turn off the child device? I don't have lights on this fan and would like it to not appear as a device (since I can't simply delete the child device in HE).

**Comment by bhamiltoncx** [comment]
I can put together an option for that. I wonder if there's any way we can
query the device to see if it has a light..

**Comment by brad628** [comment]
Thanks! Doubtful on the query, since their own app has no option/setting, and the light option displays there even if you don’t have one (I can turn on my phantom light if I please!). When doing the actual fan hardware installation, I noticed that there’s no option to make a controller change and wires simply terminate in the housing when a lighting fixture isn’t installed.

**Comment by bhamiltoncx** [comment]
@kcdk99 , just to confirm, could you please toggle "Enable debug logging" on for the main device, click "Refresh", then go to the logs tab -> Past logs and send me the output that looks like:

```
dev:1082021-09-15 08:57:48.899 debugGot response: [clientId:MF_C8934683CDDE, lightOn:false, fanOn:false, lightBrightness:100, fanSpeed:2, fanDirection:forward, rfPairModeActive:false, resetRfPairList:false, factoryReset:false, awayModeEnabled:false, fanSleepTimer:0, lightSleepTimer:0, decommission:false, schedule:, adaptiveLearning:false]
```

?

Just want to make 100% sure I can't detect this automatically before I add an option.

**Comment by brad628** [comment]
Sure thing, here ya go:
`dev:2492021-09-15 12:11:05.534 debugGot response: [clientId:MF_4C11AEE5A8BC, cloudPort:8883, lightOn:false, fanOn:false, lightBrightness:50, fanSpeed:5, fanDirection:reverse, wind:false, windSpeed:3, rfPairModeActive:false, resetRfPairList:false, factoryReset:false, awayModeEnabled:false, fanTimer:0, lightTimer:0, decommission:false, schedule:, adaptiveLearning:false, userData:local_wifi, timezone:EST5EDT]`

**Comment by bhamiltoncx** [comment]
Yup, no way around it, have to add an option. Thanks for confirming!

**Comment by bhamiltoncx** [comment]
OK, should be fixed. I added a new "Enable light" toggle option (on by default). Turn it off to disable the light.

Thanks for the report!

**Comment by brad628** [comment]
Thanks! Not currently home, but appears to be working as far as I can tell remotely. I’ll give it a try when I’m back on Saturday and let you know if I see any issues. Thanks again!

**Comment by brad628** [comment]
@bhamiltoncx - just a quick follow-up note, I was looking at the debug logs, and it looks like the driver is attempting to delete the child device upon each refresh, even though it no longer exists. I had a high state count so I reduced polling to 1800 since I typically control the fan programmatically. I realize light installed status can't be determined, but perhaps the deletion attempt can be excluded if light set to false and deletion has already been excluded?

```dev:2492021-09-26 10:53:50.716 debugScheduling next poll for 1800
dev:2492021-09-26 10:53:50.714 debugDeleting child dimmer device 346a6667-01df-4b52-ae1b-e01548583bb9-light
dev:2492021-09-26 10:53:50.707 debugGot response: [clientId:MF_4C11AEE5A8BC, cloudPort:8883, lightOn:false, fanOn:false, lightBrightness:50, fanSpeed:2, fanDirection:reverse, wind:false, windSpeed:3, rfPairModeActive:false, resetRfPairList:false, factoryReset:false, awayModeEnabled:false, fanTimer:0, lightTimer:0, decommission:false, schedule:, adaptiveLearning:false, userData:cloud, timezone:EST5EDT]
dev:2492021-09-26 10:53:50.616 debugSending request: [queryDynamicShadowData:1]
dev:2492021-09-26 10:53:50.605 debugFetching current fan state
dev:2492021-09-26 10:53:50.604 debugRunning poll
dev:2492021-09-26 10:23:50.579 debugScheduling next poll for 1800
dev:2492021-09-26 10:23:50.577 debugDeleting child dimmer device 346a6667-01df-4b52-ae1b-e01548583bb9-light
dev:2492021-09-26 10:23:50.569 debugGot response: [clientId:MF_4C11AEE5A8BC, cloudPort:8883, lightOn:false, fanOn:false, lightBrightness:50, fanSpeed:2, fanDirection:reverse, wind:false, windSpeed:3, rfPairModeActive:false, resetRfPairList:false, factoryReset:false, awayModeEnabled:false, fanTimer:0, lightTimer:0, decommission:false, schedule:, adaptiveLearning:false, userData:cloud, timezone:EST5EDT]
dev:2492021-09-26 10:23:50.492 debugSending request: [queryDynamicShadowData:1]
dev:2492021-09-26 10:23:50.481 debugFetching current fan state
dev:2492021-09-26 10:23:50.480 debugRunning poll```

**Comment by bhamiltoncx** [comment]
I don't think it's any more expensive to delete a non-existent child device than it would be to put in extra logic to try to remember the state of the child device. Probably best just to disable debug logs now. :)

**Comment by brad628** [comment]
If that’s the case, agreed. I was just thinking of a situation where a **noLight** property could be set to eliminate the need for a deletion request on every refresh.
